// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5JMXeQFcFX0rcbSZ33QsGiw7waA-Bq-I',
    appId: '1:247982645339:web:930b0b1554837e7df85f7e',
    messagingSenderId: '247982645339',
    projectId: 'yonetici-fca27',
    authDomain: 'yonetici-fca27.firebaseapp.com',
    storageBucket: 'yonetici-fca27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfQuKh6_krAeWJpJf4pZ1_WV6sJvrv9U',
    appId: '1:247982645339:android:148fef6452598764f85f7e',
    messagingSenderId: '247982645339',
    projectId: 'yonetici-fca27',
    storageBucket: 'yonetici-fca27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8n8s6crQagESHIGZlq27We9mWvGBQIA',
    appId: '1:247982645339:ios:8e336ef9b9c7e266f85f7e',
    messagingSenderId: '247982645339',
    projectId: 'yonetici-fca27',
    storageBucket: 'yonetici-fca27.appspot.com',
    iosBundleId: 'com.example.yoneticiPaneli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8n8s6crQagESHIGZlq27We9mWvGBQIA',
    appId: '1:247982645339:ios:8e336ef9b9c7e266f85f7e',
    messagingSenderId: '247982645339',
    projectId: 'yonetici-fca27',
    storageBucket: 'yonetici-fca27.appspot.com',
    iosBundleId: 'com.example.yoneticiPaneli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5JMXeQFcFX0rcbSZ33QsGiw7waA-Bq-I',
    appId: '1:247982645339:web:fd84412738612e71f85f7e',
    messagingSenderId: '247982645339',
    projectId: 'yonetici-fca27',
    authDomain: 'yonetici-fca27.firebaseapp.com',
    storageBucket: 'yonetici-fca27.appspot.com',
  );
}
